name: multi_expansion_card
description: A customizable Flutter widget that allows multiple expansion tiles/cards with easy state management and styling.
version: 0.0.1
homepage: https://github.com/AdeebAnvar/multi_expansion_card
repository: https://github.com/AdeebAnvar/multi_expansion_card

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
